# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alert.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61lert.proto\x12\x04mace\"\xaf\x01\n\x05\x41lert\x12\x10\n\x08\x61lert_id\x18\x01 \x01(\t\x12\x11\n\trule_name\x18\x02 \x01(\t\x12 \n\x08severity\x18\x03 \x01(\x0e\x32\x0e.mace.Severity\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x0c\n\x04tgid\x18\x05 \x01(\r\x12\x14\n\x0cprocess_name\x18\x06 \x01(\t\x12\x14\n\x0ctimestamp_ns\x18\x07 \x01(\x04\x12\x14\n\x0c\x63ontext_json\x18\x08 \x01(\t\")\n\nAlertBatch\x12\x1b\n\x06\x61lerts\x18\x01 \x03(\x0b\x32\x0b.mace.Alert*\x88\x01\n\x08Severity\x12\x18\n\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x11\n\rSEVERITY_INFO\x10\x01\x12\x10\n\x0cSEVERITY_LOW\x10\x02\x12\x13\n\x0fSEVERITY_MEDIUM\x10\x03\x12\x11\n\rSEVERITY_HIGH\x10\x04\x12\x15\n\x11SEVERITY_CRITICAL\x10\x05\x42-Z+github.com/mace-ebpf/sdk/pkg/mace/maceprotob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'alert_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z+github.com/mace-ebpf/sdk/pkg/mace/maceproto'
  _SEVERITY._serialized_start=243
  _SEVERITY._serialized_end=379
  _ALERT._serialized_start=22
  _ALERT._serialized_end=197
  _ALERTBATCH._serialized_start=199
  _ALERTBATCH._serialized_end=240
# @@protoc_insertion_point(module_scope)
