// Package mace is a thin Go client over the Mace-eBPF Rust core (statically linked), with channel-based delivery of structured events.
//
// Log level FFI: see mace_set_log_level in mace-ebpf/include/mace.h — wrapped by [SetLogLevel] / [InitEngineWithConfig].
package mace

/*
#cgo CFLAGS: -I${SRCDIR}/../../../mace-ebpf/include
// Static link the Rust core (no libmace_ebpf.so / LD_LIBRARY_PATH). Default: debug — `cargo build -p mace-ebpf`.
// Release: `cargo build --release -p mace-ebpf` then `go build -tags mace_static_release`.
#cgo !mace_static_release LDFLAGS: ${SRCDIR}/../../../target/debug/libmace_ebpf.a -ldl -lpthread -lm -lgcc_s
#cgo mace_static_release LDFLAGS: ${SRCDIR}/../../../target/release/libmace_ebpf.a -ldl -lpthread -lm -lgcc_s
#include "mace.h"
#include <stdlib.h>

// mace_go_json_event_callback is generated by cgo from the Go //export below.
extern void mace_go_json_event_callback(char *json_utf8);

static void mace_register_json_callback_bridge(void) {
	mace_register_event_callback((MaceJsonCallback)mace_go_json_event_callback);
}
*/
import "C"

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"sync"
	"unsafe"
)

// MaceEvent is the JSON shape emitted by the Rust pipeline after rule evaluation
// (serde_json of `mace_ebpf::StandardizedEvent`). All syscall observations are delivered here;
// use MatchedRules / SuppressedBy to classify alerts vs telemetry.
type MaceEvent struct {
	Timestamp    uint64   `json:"timestamp"`
	PID          uint32   `json:"pid"`
	UID          uint32   `json:"uid"`
	Username     string   `json:"username"`
	ProcessName  string   `json:"process_name"`
	SyscallName  string   `json:"syscall_name"`
	Cmdline      string   `json:"cmdline"`
	Arguments    []string `json:"arguments"`
	MatchedRules []string `json:"matched_rules"`
	// SuppressedBy lists suppression entry ids when alerts were suppressed (matched_rules still populated).
	SuppressedBy []string `json:"suppressed_by,omitempty"`
}

// Client receives structured JSON events from the Rust core on a buffered channel (single active client per process).
type Client struct {
	eventsChan chan MaceEvent
}

var (
	activeClientMu sync.Mutex
	activeClient   *Client // non-nil while Rust JSON callback may fire
)

const defaultEventBuffer = 256

// NewClient registers the global FFI JSON sink and returns a client whose [Client.Events] channel receives [MaceEvent] values.
// Only one [Client] may be active at a time; a second [NewClient] returns an error until the first is [Client.Close]d.
// eventBuffer is the channel buffer capacity; values < 1 default to 256.
func NewClient(eventBuffer int) (*Client, error) {
	if eventBuffer < 1 {
		eventBuffer = defaultEventBuffer
	}
	activeClientMu.Lock()
	defer activeClientMu.Unlock()
	if activeClient != nil {
		return nil, errors.New("mace: NewClient: another client is already active; Close it first")
	}
	c := &Client{eventsChan: make(chan MaceEvent, eventBuffer)}
	activeClient = c
	C.mace_register_json_callback_bridge()
	return c, nil
}

// Events returns the receive-only channel fed from the C/Rust JSON callback. The channel is closed when [Client.Close] is called.
func (c *Client) Events() <-chan MaceEvent {
	return c.eventsChan
}

// Close unregisters the FFI callback, clears the active client, and closes the events channel.
// It is safe to call once; subsequent calls return an error.
func (c *Client) Close() error {
	activeClientMu.Lock()
	defer activeClientMu.Unlock()
	if activeClient != c {
		return errors.New("mace: Close: invalid or already closed client")
	}
	activeClient = nil
	C.mace_unregister_event_callback()
	close(c.eventsChan)
	return nil
}

func pushMaceEventJSON(payload string) {
	activeClientMu.Lock()
	c := activeClient
	activeClientMu.Unlock()
	if c == nil {
		return
	}
	var ev MaceEvent
	if err := json.Unmarshal([]byte(payload), &ev); err != nil {
		fmt.Fprintf(os.Stderr, "mace: MaceEvent JSON decode error: %v (len=%d)\n", err, len(payload))
		return
	}
	// Blocking send applies backpressure if the consumer is slow (Rust invokes this from the pipeline worker).
	c.eventsChan <- ev
}

// InitEngine resets embedded engine state in Rust (call before LoadRules / StartPipeline).
func InitEngine() error {
	return InitEngineWithConfig(EngineConfig{})
}

// EngineConfig optional knobs for [InitEngineWithConfig].
type EngineConfig struct {
	// LogLevel, if non-nil, calls [SetLogLevel] after init (overrides MACE_LOG_LEVEL applied inside Rust init).
	LogLevel *LogLevel
}

// InitEngineWithConfig calls mace_engine_init then applies cfg (e.g. log level override).
func InitEngineWithConfig(cfg EngineConfig) error {
	if C.mace_engine_init() != 0 {
		return errors.New("mace: InitEngine failed")
	}
	if cfg.LogLevel != nil {
		return SetLogLevel(*cfg.LogLevel)
	}
	return nil
}

// LoadRules validates and stages inline YAML for the embedded engine (must call before StartPipeline).
func LoadRules(yaml string) error {
	if yaml == "" {
		return errors.New("mace: empty yaml")
	}
	cs, err := allocCString(yaml)
	if err != nil {
		return err
	}
	defer cs.free()
	if C.mace_load_rules(cs.ptr) != 0 {
		return errors.New("mace: LoadRules failed (invalid yaml or engine error)")
	}
	return nil
}

// LoadRulesFile validates rules at path and stages file-based loading with hot-reload (must call before StartPipeline).
func LoadRulesFile(path string) error {
	if path == "" {
		return errors.New("mace: empty rules path")
	}
	cs, err := allocCString(path)
	if err != nil {
		return err
	}
	defer cs.free()
	if C.mace_load_rules_file(cs.ptr) != 0 {
		return fmt.Errorf("mace: LoadRulesFile failed for %q", path)
	}
	return nil
}

// StartPipeline starts the eBPF sensor + rule pipeline in a background thread (requires root/CAP_BPF).
func StartPipeline() error {
	if C.mace_start_pipeline() != 0 {
		return errors.New("mace: StartPipeline failed (need root? BPF unsupported? or load rules first)")
	}
	return nil
}

// StopPipeline stops the embedded engine thread.
func StopPipeline() error {
	if C.mace_stop_pipeline() != 0 {
		return errors.New("mace: StopPipeline failed")
	}
	return nil
}

// LogLevel is the argument type for [SetLogLevel], matching C int32_t level (0…4) for mace_set_log_level.
type LogLevel int32

const (
	LogLevelTrace      LogLevel = 0 // MACE_LOG_LEVEL=TRACE
	LogLevelInfo       LogLevel = 1
	LogLevelSuppressed LogLevel = 2
	LogLevelEvent      LogLevel = 3
	LogLevelAlert      LogLevel = 4
)

// SetLogLevel wraps mace_set_log_level: minimum severity for Rust [Mace][LEVEL] stderr lines.
// Valid range is [LogLevelTrace, LogLevelAlert]; other values return an error (no C heap allocation).
// Safe to call before or after [InitEngine]; thread-safe in Rust.
func SetLogLevel(level LogLevel) error {
	rc := C.mace_set_log_level(C.int32_t(level))
	if rc != 0 {
		return fmt.Errorf("mace: SetLogLevel(%d) failed (rc=%d)", level, rc)
	}
	return nil
}

type cString struct {
	ptr *C.char
}

func allocCString(s string) (cString, error) {
	if s == "" {
		return cString{}, errors.New("mace: empty string")
	}
	p := C.CString(s)
	if p == nil {
		return cString{}, errors.New("mace: C.CString failed")
	}
	return cString{ptr: p}, nil
}

func (c cString) free() {
	if c.ptr != nil {
		C.free(unsafe.Pointer(c.ptr))
	}
}

//export mace_go_json_event_callback
func mace_go_json_event_callback(cjson *C.char) { // cgo passes char* (mutable pointer)
	if cjson == nil {
		return
	}
	s := C.GoString(cjson)
	pushMaceEventJSON(s)
}
