// Package aegis is a thin Go client over the Aegis-eBPF Rust core (statically linked), including JSON event callbacks.
//
// Log level FFI: see aegis_set_log_level in aegis-ebpf/include/aegis.h — wrapped by [SetLogLevel] / [InitEngineWithConfig].
package aegis

/*
#cgo CFLAGS: -I${SRCDIR}/../../../aegis-ebpf/include
// Static link the Rust core (no libaegis_ebpf.so / LD_LIBRARY_PATH). Default: debug — `cargo build -p aegis-ebpf`.
// Release: `cargo build --release -p aegis-ebpf` then `go build -tags aegis_static_release`.
#cgo !aegis_static_release LDFLAGS: ${SRCDIR}/../../../target/debug/libaegis_ebpf.a -ldl -lpthread -lm -lgcc_s
#cgo aegis_static_release LDFLAGS: ${SRCDIR}/../../../target/release/libaegis_ebpf.a -ldl -lpthread -lm -lgcc_s
#include "aegis.h"
#include <stdlib.h>

// aegis_go_json_event_callback is generated by cgo from the Go //export below.
extern void aegis_go_json_event_callback(char *json_utf8);

static void aegis_register_json_callback_bridge(void) {
	register_event_callback((AegisJsonCallback)aegis_go_json_event_callback);
}
*/
import "C"

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"sync"
	"unsafe"
)

var (
	userCallbackMu sync.RWMutex
	userCallback   func(StandardizedEvent)
)

// InitEngine resets embedded engine state in Rust (call before LoadRules / StartPipeline).
func InitEngine() error {
	return InitEngineWithConfig(EngineConfig{})
}

// EngineConfig optional knobs for [InitEngineWithConfig].
type EngineConfig struct {
	// LogLevel, if non-nil, calls [SetLogLevel] after init (overrides AEGIS_LOG_LEVEL applied inside Rust init).
	LogLevel *LogLevel
}

// InitEngineWithConfig calls aegis_engine_init then applies cfg (e.g. log level override).
func InitEngineWithConfig(cfg EngineConfig) error {
	if C.aegis_engine_init() != 0 {
		return errors.New("aegis: InitEngine failed")
	}
	if cfg.LogLevel != nil {
		return SetLogLevel(*cfg.LogLevel)
	}
	return nil
}

// LoadRules validates and stages inline YAML for the embedded engine (must call before StartPipeline).
func LoadRules(yaml string) error {
	if yaml == "" {
		return errors.New("aegis: empty yaml")
	}
	cs, err := allocCString(yaml)
	if err != nil {
		return err
	}
	defer cs.free()
	if C.aegis_load_rules(cs.ptr) != 0 {
		return errors.New("aegis: LoadRules failed (invalid yaml or engine error)")
	}
	return nil
}

// LoadRulesFile validates rules at path and stages file-based loading with hot-reload (must call before StartPipeline).
func LoadRulesFile(path string) error {
	if path == "" {
		return errors.New("aegis: empty rules path")
	}
	cs, err := allocCString(path)
	if err != nil {
		return err
	}
	defer cs.free()
	if C.aegis_load_rules_file(cs.ptr) != 0 {
		return fmt.Errorf("aegis: LoadRulesFile failed for %q", path)
	}
	return nil
}

// StartPipeline starts the eBPF sensor + rule pipeline in a background thread (requires root/CAP_BPF).
func StartPipeline() error {
	if C.aegis_start_pipeline() != 0 {
		return errors.New("aegis: StartPipeline failed (need root? BPF unsupported? or load rules first)")
	}
	return nil
}

// StopPipeline stops the embedded engine thread.
func StopPipeline() error {
	if C.aegis_stop_pipeline() != 0 {
		return errors.New("aegis: StopPipeline failed")
	}
	return nil
}

// LogLevel is the argument type for [SetLogLevel], matching C int32_t level (0…4) for aegis_set_log_level.
type LogLevel int32

const (
	LogLevelTrace      LogLevel = 0 // AEGIS_LOG_LEVEL=TRACE
	LogLevelInfo       LogLevel = 1
	LogLevelSuppressed LogLevel = 2
	LogLevelEvent      LogLevel = 3
	LogLevelAlert      LogLevel = 4
)

// SetLogLevel wraps aegis_set_log_level: minimum severity for Rust [Aegis][LEVEL] stderr lines.
// Valid range is [LogLevelTrace, LogLevelAlert]; other values return an error (no C heap allocation).
// Safe to call before or after [InitEngine]; thread-safe in Rust.
func SetLogLevel(level LogLevel) error {
	rc := C.aegis_set_log_level(C.int32_t(level))
	if rc != 0 {
		return fmt.Errorf("aegis: SetLogLevel(%d) failed (rc=%d)", level, rc)
	}
	return nil
}

type cString struct {
	ptr *C.char
}

func allocCString(s string) (cString, error) {
	if s == "" {
		return cString{}, errors.New("aegis: empty string")
	}
	p := C.CString(s)
	if p == nil {
		return cString{}, errors.New("aegis: C.CString failed")
	}
	return cString{ptr: p}, nil
}

func (c cString) free() {
	if c.ptr != nil {
		C.free(unsafe.Pointer(c.ptr))
	}
}

// RegisterEventCallback installs the Go handler and registers the CGO bridge with Rust.
// The C layer passes a borrowed NUL-terminated pointer; do not free it in Go.
//
// Only one callback may be active; register again returns an error until UnregisterEventCallback.
func RegisterEventCallback(cb func(StandardizedEvent)) error {
	if cb == nil {
		return errors.New("aegis: callback must be non-nil")
	}
	userCallbackMu.Lock()
	defer userCallbackMu.Unlock()
	if userCallback != nil {
		return errors.New("aegis: callback already registered; call UnregisterEventCallback first")
	}
	userCallback = cb
	C.aegis_register_json_callback_bridge()
	return nil
}

// UnregisterEventCallback clears the Go handler and unregisters the Rust JSON callback.
func UnregisterEventCallback() {
	userCallbackMu.Lock()
	defer userCallbackMu.Unlock()
	userCallback = nil
	C.unregister_event_callback()
}

//export aegis_go_json_event_callback
func aegis_go_json_event_callback(cjson *C.char) { // cgo passes char* (mutable pointer)
	if cjson == nil {
		return
	}
	s := C.GoString(cjson)

	userCallbackMu.RLock()
	cb := userCallback
	userCallbackMu.RUnlock()
	if cb == nil {
		return
	}

	var ev StandardizedEvent
	if err := json.Unmarshal([]byte(s), &ev); err != nil {
		// Silent unmarshal failures made “no alerts” look like a rule-engine bug; surface decode issues.
		fmt.Fprintf(os.Stderr, "aegis: StandardizedEvent JSON decode error: %v (len=%d)\n", err, len(s))
		return
	}
	cb(ev)
}
