// Package aegis is a thin Go client over the Aegis-eBPF Rust cdylib, including JSON event callbacks.
package aegis

/*
#cgo CFLAGS: -I${SRCDIR}/../../../aegis-ebpf/include
#cgo LDFLAGS: -L${SRCDIR}/../../../target/debug -laegis_ebpf -Wl,-rpath,${SRCDIR}/../../../target/debug
#include "aegis.h"

// aegis_go_json_event_callback is generated by cgo from the Go //export below.
extern void aegis_go_json_event_callback(char *json_utf8);

static void aegis_register_json_callback_bridge(void) {
	register_event_callback((AegisJsonCallback)aegis_go_json_event_callback);
}
*/
import "C"

import (
	"encoding/json"
	"errors"
	"sync"
)

var (
	userCallbackMu sync.RWMutex
	userCallback   func(StandardizedEvent)
)

// RegisterEventCallback installs the Go handler and registers the CGO bridge with Rust.
// The C layer passes a borrowed NUL-terminated pointer; do not free it in Go.
//
// Only one callback may be active; register again returns an error until UnregisterEventCallback.
func RegisterEventCallback(cb func(StandardizedEvent)) error {
	if cb == nil {
		return errors.New("aegis: callback must be non-nil")
	}
	userCallbackMu.Lock()
	defer userCallbackMu.Unlock()
	if userCallback != nil {
		return errors.New("aegis: callback already registered; call UnregisterEventCallback first")
	}
	userCallback = cb
	C.aegis_register_json_callback_bridge()
	return nil
}

// UnregisterEventCallback clears the Go handler and unregisters the Rust callback.
func UnregisterEventCallback() {
	userCallbackMu.Lock()
	defer userCallbackMu.Unlock()
	userCallback = nil
	C.unregister_event_callback()
}

//export aegis_go_json_event_callback
func aegis_go_json_event_callback(cjson *C.char) { // cgo passes char* (mutable pointer)
	if cjson == nil {
		return
	}
	s := C.GoString(cjson)

	userCallbackMu.RLock()
	cb := userCallback
	userCallbackMu.RUnlock()
	if cb == nil {
		return
	}

	var ev StandardizedEvent
	if err := json.Unmarshal([]byte(s), &ev); err != nil {
		return
	}
	cb(ev)
}
